CREATE TABLE dbo.Person ( 
    PersonID INT IDENTITY(1,1) PRIMARY KEY, 
    FirstName NVARCHAR(50) NOT NULL, 
    LastName NVARCHAR(50) NOT NULL, 
    DateOfBirth DATE NULL, 
    Email NVARCHAR(100) NULL, 
    PhoneNumber NVARCHAR(20) NULL, 
    CreatedAt DATETIME2 DEFAULT GETDATE() 
) 